### 게스트 모집하기
POST http://localhost:8080/games
Content-Type: application/json

{
  "content": "재밌는 농구 경기 해요~! 다 초보입니다",
  "playDate": "2023-02-01",
  "playStartTime": "11:30",
  "playTimeMinutes": 90,
  "mainAddress": "서울 영등포구 도림동 254",
  "detailAddress": "영등포 다목적 체육관 2층 201호",
  "cost": 100,
  "maxMemberCount": "5",
  "positions": [
    "C",
    "PG"
  ],
  "hostId": 1
}

### 게스트 모집 참여 신청
POST http://localhost:8080/games/2/members
Content-Type: application/json

{
  "memberId": 1
}

### 게스트 모집 참여 신청 수락
PATCH http://localhost:8080/games/2/members/3
Content-Type: application/json

{
  "status": "확정"
}
