### 새 1:1 채팅방 생성
POST http://localhost:8080/rooms/personal
Authorization:
Content-Type: application/json

{
  "receiverId": 3
}

### 특정 사용자와의 1:1 채팅방 존재 여부 조회
GET http://localhost:8080/rooms/personal/existed?receiver=2
Authorization:

### 참여중인 모든 채팅방 목록 조회(개인)
GET http://localhost:8080/rooms?type=개인
Authorization:

### 참여중인 모든 채팅방 목록 조회(게스트 모집)
GET http://localhost:8080/rooms?type=게스트
Authorization:

### 참여중인 모든 채팅방 목록 조회(크루)
GET http://localhost:8080/rooms?type=크루
Authorization:

### 단일 채팅방 정보 상세 조회
GET http://localhost:8080/rooms/1
Authorization:

### 특정 채팅방의 모든 메시지 목록 조회
GET http://localhost:8080/messages/rooms/1
Authorization:
