### 해당 사용자 알람 sse 연결
GET http://localhost:8080/alarms/subscribe
Content-Type: text/event-stream
Authorization:

### 해당 사용자 읽지 않은 알림 확인
GET http://localhost:8080/alarms/unread
Authorization:
Content-Type: application/json

### 해당 사용자의 모든 알람 삭제
DELETE http://localhost:8080/alarms
Authorization:
Content-Type: application/json
