### 회원 생성
POST http://localhost:8080/members
Content-Type: application/json
Authorization:

{
  "email": "changhyeon.h@kakao.com",
  "nickname": "창현",
  "profileImageUrl": "http://k.kakaocdn.net/dn/dpk9l1/btqmGhA2lKL/Oz0wDuJn1YV2DIn92f6DVK/img_640x640.jpg",
  "positions": [
    "SG"
  ],
  "addressDepth1": "서울시",
  "addressDepth2": "영등포구",
  "oauthId": 32014123,
  "oauthProvider": "KAKAO"
}

### 사용자 프로필 조회
GET http://localhost:8080/members/1

### 사용자가 가입한 크루 목록
GET http://localhost:8080/members/1/crews?status=확정
Authorization:

### 사용자가 만든 크루 목록 조회
GET http://localhost:8080/members/1/created-crews
Authorization:

### 사용자의 참여 확정 게스트 모집글 목록 조회
GET http://localhost:8080/members/1/games?status=확정
Authorization:

### 사용자가 만든 게스트 모집글 목록 조회
GET http://localhost:8080/members/1/created-games
Authorization:


### 사용자의 게스트 모집 참여 여부 조회
GET http://localhost:8080/members/5/games/1/registration-status
Authorization:

### 사용자의 크루 가입 여부 조회
GET http://localhost:8080/members/1/crews/2/registration-status
Authorization